<a href="https://colab.research.google.com/github/UrviSoni/pytorch_deeplearning/blob/master/AutoGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch


In [2]:
x = torch.zeros(1, requires_grad=True)
with torch.no_grad():
  y = x * 2
y.requires_grad

False

In [3]:
x = torch.randn(2,2, requires_grad=True)
print(x)

tensor([[-1.0440,  0.7782],
        [-1.5013, -0.6443]], requires_grad=True)


In [4]:
y = x ** 2
print(y)

tensor([[1.0899, 0.6056],
        [2.2538, 0.4151]], grad_fn=<PowBackward0>)


In [5]:
## grad_fn shows the function that generated this variable
print(y.grad_fn)

In [6]:
z = y.mean()
print(z)

tensor(1.0911, grad_fn=<MeanBackward1>)


In [7]:
print(x.grad)

None


In [8]:
z.backward()
print(x.grad)
print(x/2)

tensor([[-0.5220,  0.3891],
        [-0.7506, -0.3222]])
tensor([[-0.5220,  0.3891],
        [-0.7506, -0.3222]], grad_fn=<DivBackward0>)
